;;; chatgpt-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from chatgpt.el

(autoload 'chatgpt-new "chatgpt" "\
Run a new instance of ChatGPT." t)
(autoload 'chatgpt "chatgpt" "\
Start ChatGPT with existing instance, else create a new instance." t)
(register-definition-prefixes "chatgpt" '("chatgpt-"))

;;; End of scraped data

(provide 'chatgpt-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; chatgpt-autoloads.el ends here
